# -*- coding: utf-8 -*-
"""Scikit_learn1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qj7dbNO5CBZ6xs_Rr_jqCOvIcCSq3ZHK

importing the scikit library
"""

import sklearn

"""importing the iris dataset from the sclearn datasets"""

from sklearn.datasets import load_iris

"""this command will load all the data from the iris data set such as data, target,feature names, description etc.."""

load_iris() //

"""this command will only print the data and target values that we used to store in x and y as the model input and output variables"""

load_iris(return_X_y = True) //

"""here we are taking out the data and target values from the iris data set and storing in the x and y variables we can also use

---


 x,y = load_iris(return_X_y = True)
"""

X = load_iris().data
y = load_iris().target

"""importing the linarregression model from sklearn"""

from sklearn.linear_model import LinearRegression

"""storing the linear regression model into the variable called Model"""

Model = LinearRegression()

"""fitting the X,y values into the Model that we already created"""

Model.fit(X,y)

"""here the model is predicting the target values with is a 1D array ."""

Model.predict(X)

"""importing KneighborsRegressor from the sklearn library called neighbors"""

from sklearn.neighbors import KNeighborsRegressor

"""storing the kneighborsRegressor in the variable called mod"""

mod = KNeighborsRegressor()

mod.fit(X,y)

"""predicting the target values from the data (X)"""

mod.predict(X)

"""here, we have created a scatter plot and we have plotted the predicted values in the x axis and target values in the y axis and we can see from the graph that our knn model predicts accurately the targer values."""

import matplotlib.pyplot as plt
pred = mod.predict(X)
plt.scatter(pred,y)

